### PR TITLE
Decode the Protocol Buffers from the loggregator

### PR DESCRIPTION
**Pull request by nsand**
In using the API, I noticed that the results of `getRecent` came back with text that didn't look very great. This PR aim to address this by decoding the multipart protocol buffer returned from the loggregator API request, and in the end provides an array of message objects conforming to the protocol definition provided by cloud foundry https://github.com/cloudfoundry/loggregatorlib/blob/master/logmessage/log_message.proto

### CODE REVIEW

**Comment by nsand** [comment]
Hi @cphrmky @jsloyer any changes that you need me to make for this, or do you think it's ok to merge?

**Comment by aeweidne** [comment]
@nsand I rolled your changes into #22 and got the tests passing if that gives @cphrmky @jsloyer more confidence

**Comment by jsloyer** [comment]
Going to close this one out since #22 has been merged in.

**Comment by jsloyer** [comment]
@nsand, @aeweidne just published `0.13.19`.

**Pull request closed without merging**
